spring:
  security:
    ignored: /**
  h2:
    console:
      enabled: true
      path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///euromoby?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:euromoby;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
