server:
  port: 8080

spring:
  profiles:
    active: development
  application:
    name: 'User API'
  data:
    mongodb:
      database: 'user-api-v1'

logging:
  level:
    org:
      springframework:
        security: 'DEBUG'
