logging:
  level:
    org.springframework.r2dbc: INFO
    web: INFO
server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  r2dbc:
    url: r2dbc:h2:mem:///euromoby?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:euromoby;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    user: sa
    password:
springdoc:
  api-docs:
    path: /api-definitions
  swagger-ui:
    path: /apidoc.html
    operationsSorter: method
auth:
  jwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
