version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - sms-api-mongodb-data:/data/db

  api:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sms_api

volumes:
  sms-api-mongodb-data:
