server:
  port: 8081

spring:
  profiles:
    active: development
  application:
    name: 'Auth API'
  data:
    mongodb:
      database: 'users-v1'

jwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize

logging:
  level:
    org:
      springframework:
        security: 'DEBUG'
